server:
  port: 8942
---
spring:
  cloud:
    consul:
      host: "${CONSUL_HOST:localhost}"
      port: 8500
      discovery:
        heartbeat:
          enabled: false
        prefer-ip-address: true
        instance-id: ${spring.application.name}-${random.uuid}
        health-check-path: /actuator/health
        health-check-interval: 60s
        service-name: ${spring.application.name}
        register-health-check: true
---
spring:
  application:
    name: trigger_service
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  messages:
    basename: i18n/messages
  jackson:
    time-zone: GMT+7
    property-naming-strategy: SNAKE_CASE
  http:
    codecs:
      max-in-memory-size: 100MB
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
        generate_statistics: false
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true
        query:
          fail_on_pagination_over_collection_fetch: true
          in_clause_parameter_padding: true
  security:
    oauth2:
      client:
        provider:
          oidc:
            token-uri: ${keycloak.server-url}/realms/${keycloak.realm}/protocol/openid-connect/token
        registration:
          oidc:
            client-id: ${keycloak.client-id}
            client-secret: ${keycloak.client-secret}
            authorization-grant-type: ${keycloak.grant-type}
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs
      keycloak:
        client-id: ${keycloak.client-id}
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 25
            threadPriority: 5
          scheduler:
            instanceName: MyClusteredScheduler
            instanceId: AUTO
            batchTriggerAcquisitionMaxCount: 5
          jobStore:
            misfireThreshold: 60000
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            acquireTriggersWithinLock: true
            dataSource: jobDataSource
            clusterCheckinInterval: 20000
            useProperties: true
            isClustered: true
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
          dataSource:
            jobDataSource:
              driver: org.postgresql.Driver
              provider: hikaricp
              URL: jdbc:postgresql://localhost:5434/trigger
              user: admin
              password: admin
    wait-for-jobs-to-complete-on-shutdown: true
    jdbc:
      initialize-schema: never
---
keycloak:
  client-id: "${KEYCLOAK_CLIENT_ID:ezbuy-client}"
  client-secret: "${KEYCLOAK_CLIENT_SECRET:5dnfDh6XitmAMc7vQUNxGkJw0HF4e9tI}"
  realm: "${KEYCLOAK_REALM:ezbuy-server}"
  server-url: "${KEYCLOAK_SERVER_URL:http://localhost:8080}"
  grant-type: "${KEYCLOAK_GRANT_TYPE:password}" #client_credentials
  host: "${KEYCLOAK_HOST:localhost}"
---
cron-job:
  profiles:
    - name: SYNC_USER_PROFILE
      cron-job: 0/3 * * * * ?
    - name: SYNC_ORDER_STATE
      cron-job: 0/3 * * * * ?
    - name: SYNC_PRODUCT_FILTER
      cron-job: 0/3 * * * * ?
    - name: SYNC_RETRY
      cron-job: 0/3 * * * * ?
    - name: SYNC_PASSWORD
      cron-job: 0 */5 * * * ?
    - name: SYNC_SUBSCRIBER
      cron-job: 0 */1 * * * ?
    - name: SYNC_ELASTICSEARCH
      cron-job: 0 */5 * * * ?
    - name: SYNC_CUSTOMER_INFO
      cron-job: 0 * * ? * *
    - name: RETRY_SYNC_CUSTOMER_INFO
      cron-job: 0 1 * ? * *
    - name: SYNC_EVENT_HISTORY
      cron-job: 0/5 * * * * ?
    - name: SYNC_TRANSACTION
      cron-job: 0 1 1 * * ?
    - name: SYNC_SIGN_HASH_JOB
      cron-job: 0 */1 * * * ?
    - name: SYNC_DAILY_REPORT
      cron-job: 0 0 2 * * ?
    - name: UNLOCK_VOUCHER
      cron-job: 0 */1 * * * ?
    - name: UNLOCK_VOUCHER_TRANSACTION
      cron-job: 0 */1 * * * ?
    - name: INSERT_VOUCHER
      cron-job: 0 */1 * * * ?
---
client:
  product:
    internal-oauth: true
    address: http://localhost:8083/
    name: productClient
  order:
    internal-oauth: true
    address: http://localhost:8932/
    name: orderClient
  setting:
    internal-oauth: true
    address: http://localhost:8082/
    name: settingClient
---
springdoc:
  api-docs:
    path: /v1/auth/v3/api-docs
  swagger-ui:
    path: /v1/auth/swagger-ui.html
    url: /v1/auth/v3/api-docs
---
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always