[versions]
com-google-code-gson-gson = "2.11.0"
com-sun-activation-jakarta-activation = "2.0.1"
com-zaxxer-hikaricp = "5.1.0"
commons-io-commons-io = "2.16.1"
io-github-hoangtien2k3-reactify-core = "1.3.0"
junit-junit = "4.13.1"
org-apache-commons-commons-compress = "1.26.2"
org-apache-mina-mina-core = "2.2.4"
org-apache-poi-poi = "5.1.0"
org-apache-poi-poi-ooxml = "5.4.0"
org-awaitility-awaitility = "4.2.2"
org-json-json = "20240303"
org-jsoup-jsoup = "1.18.1"
org-keycloak-bom-keycloak-adapter-bom = "25.0.6"
org-keycloak-keycloak-admin-client = "25.0.6"
org-springdoc-springdoc-openapi-starter-webflux-api = "2.2.0"
org-springframework-boot-spring-boot-starter-data-elasticsearch = "3.5.3"
org-springframework-boot-spring-boot-starter-mail = "3.5.3"
org-springframework-boot-spring-boot-starter-quartz = "3.5.3"
org-springframework-boot-spring-boot-starter-thymeleaf = "3.5.3"
org-springframework-cloud-spring-cloud-gateway-server-webflux = "4.3.0"
org-springframework-cloud-spring-cloud-starter-consul-discovery = "4.3.0"
org-springframework-data-spring-data-elasticsearch = "5.4.1"
net-logstash-logback-logstash-logback-encoder = "8.1"
org-testcontainers-elasticsearch = "1.12.2"

com-github-ben-manes-caffeine-caffeine = "3.1.8"
io-micrometer-micrometer-core = "1.14.4"
io-micrometer-micrometer-tracing-bridge-brave = "1.4.3"
io-minio-minio = "8.5.11"
io-projectreactor-addons-reactor-extra = "3.5.2"
io-r2dbc-r2dbc-pool = "1.0.2.RELEASE"
javax-annotation-javax-annotation-api = "1.3.2"
javax-xml-bind-jaxb-api = "2.3.1"
org-modelmapper-modelmapper = "3.2.0"
org-reflections-reflections = "0.10.2"
org-springframework-boot-spring-boot-starter-aop = "3.3.5"
org-springframework-boot-spring-boot-starter-data-r2dbc = "3.3.5"
org-springframework-boot-spring-boot-starter-oauth2-client = "3.3.5"
org-springframework-boot-spring-boot-starter-oauth2-resource-server = "3.3.5"
org-springframework-boot-spring-boot-starter-webflux = "3.3.5"

[libraries]
com-google-code-gson-gson = { module = "com.google.code.gson:gson", version.ref = "com-google-code-gson-gson" }
com-sun-activation-jakarta-activation = { module = "com.sun.activation:jakarta.activation", version.ref = "com-sun-activation-jakarta-activation" }
com-zaxxer-hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "com-zaxxer-hikaricp" }
commons-io-commons-io = { module = "commons-io:commons-io", version.ref = "commons-io-commons-io" }
io-github-hoangtien2k3-reactify-core = { module = "io.github.hoangtien2k3:reactify-core", version.ref = "io-github-hoangtien2k3-reactify-core" }
junit-junit = { module = "junit:junit", version.ref = "junit-junit" }
org-apache-commons-commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "org-apache-commons-commons-compress" }
org-apache-mina-mina-core = { module = "org.apache.mina:mina-core", version.ref = "org-apache-mina-mina-core" }
org-apache-poi-poi = { module = "org.apache.poi:poi", version.ref = "org-apache-poi-poi" }
org-apache-poi-poi-ooxml = { module = "org.apache.poi:poi-ooxml", version.ref = "org-apache-poi-poi-ooxml" }
org-awaitility-awaitility = { module = "org.awaitility:awaitility", version.ref = "org-awaitility-awaitility" }
org-json-json = { module = "org.json:json", version.ref = "org-json-json" }
org-jsoup-jsoup = { module = "org.jsoup:jsoup", version.ref = "org-jsoup-jsoup" }
org-keycloak-bom-keycloak-adapter-bom = { module = "org.keycloak.bom:keycloak-adapter-bom", version.ref = "org-keycloak-bom-keycloak-adapter-bom" }
org-keycloak-keycloak-admin-client = { module = "org.keycloak:keycloak-admin-client", version.ref = "org-keycloak-keycloak-admin-client" }
org-springdoc-springdoc-openapi-starter-webflux-api = { module = "org.springdoc:springdoc-openapi-starter-webflux-api", version.ref = "org-springdoc-springdoc-openapi-starter-webflux-api" }
org-springframework-boot-spring-boot-starter-data-elasticsearch = { module = "org.springframework.boot:spring-boot-starter-data-elasticsearch", version.ref = "org-springframework-boot-spring-boot-starter-data-elasticsearch" }
org-springframework-boot-spring-boot-starter-mail = { module = "org.springframework.boot:spring-boot-starter-mail", version.ref = "org-springframework-boot-spring-boot-starter-mail" }
org-springframework-boot-spring-boot-starter-quartz = { module = "org.springframework.boot:spring-boot-starter-quartz", version.ref = "org-springframework-boot-spring-boot-starter-quartz" }
org-springframework-boot-spring-boot-starter-thymeleaf = { module = "org.springframework.boot:spring-boot-starter-thymeleaf", version.ref = "org-springframework-boot-spring-boot-starter-thymeleaf" }
org-springframework-cloud-spring-cloud-gateway-server-webflux = { module = "org.springframework.cloud:spring-cloud-gateway-server-webflux", version.ref = "org-springframework-cloud-spring-cloud-gateway-server-webflux" }
org-springframework-cloud-spring-cloud-starter-consul-discovery = { module = "org.springframework.cloud:spring-cloud-starter-consul-discovery", version.ref = "org-springframework-cloud-spring-cloud-starter-consul-discovery" }
org-springframework-data-spring-data-elasticsearch = { module = "org.springframework.data:spring-data-elasticsearch", version.ref = "org-springframework-data-spring-data-elasticsearch" }
net-logstash-logback = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "net-logstash-logback-logstash-logback-encoder" }
org-testcontainers-elasticsearch = { module = "org.testcontainers:elasticsearch", version.ref = "org-testcontainers-elasticsearch" }

com-github-ben-manes-caffeine-caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "com-github-ben-manes-caffeine-caffeine" }
io-micrometer-micrometer-core = { module = "io.micrometer:micrometer-core", version.ref = "io-micrometer-micrometer-core" }
io-micrometer-micrometer-tracing-bridge-brave = { module = "io.micrometer:micrometer-tracing-bridge-brave", version.ref = "io-micrometer-micrometer-tracing-bridge-brave" }
io-minio-minio = { module = "io.minio:minio", version.ref = "io-minio-minio" }
io-projectreactor-addons-reactor-extra = { module = "io.projectreactor.addons:reactor-extra", version.ref = "io-projectreactor-addons-reactor-extra" }
io-r2dbc-r2dbc-pool = { module = "io.r2dbc:r2dbc-pool", version.ref = "io-r2dbc-r2dbc-pool" }
javax-annotation-javax-annotation-api = { module = "javax.annotation:javax.annotation-api", version.ref = "javax-annotation-javax-annotation-api" }
javax-xml-bind-jaxb-api = { module = "javax.xml.bind:jaxb-api", version.ref = "javax-xml-bind-jaxb-api" }
org-modelmapper-modelmapper = { module = "org.modelmapper:modelmapper", version.ref = "org-modelmapper-modelmapper" }
org-reflections-reflections = { module = "org.reflections:reflections", version.ref = "org-reflections-reflections" }
org-springframework-boot-spring-boot-starter-aop = { module = "org.springframework.boot:spring-boot-starter-aop", version.ref = "org-springframework-boot-spring-boot-starter-aop" }
org-springframework-boot-spring-boot-starter-data-r2dbc = { module = "org.springframework.boot:spring-boot-starter-data-r2dbc", version.ref = "org-springframework-boot-spring-boot-starter-data-r2dbc" }
org-springframework-boot-spring-boot-starter-oauth2-client = { module = "org.springframework.boot:spring-boot-starter-oauth2-client", version.ref = "org-springframework-boot-spring-boot-starter-oauth2-client" }
org-springframework-boot-spring-boot-starter-oauth2-resource-server = { module = "org.springframework.boot:spring-boot-starter-oauth2-resource-server", version.ref = "org-springframework-boot-spring-boot-starter-oauth2-resource-server" }
org-springframework-boot-spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux", version.ref = "org-springframework-boot-spring-boot-starter-webflux" }